import { ChevronDown, Edit, Plus, Trash2 } from 'lucide-react-native';
import { useState } from 'react';
import { ActivityIndicator, Alert, Keyboard, Modal, ScrollView, Switch, Text, TextInput, TouchableOpacity, TouchableWithoutFeedback, View } from 'react-native';
import { useLeague } from '../../context/LeagueContext';
import { Season } from '../../types';

export default function ManageSeasonsScreen() {
    const { seasons, addSeason, updateSeason, deleteSeason, isLoading } = useLeague();
    const [isModalVisible, setModalVisible] = useState(false);
    const [saving, setSaving] = useState(false);

    // Edit Mode State
    const [isEditing, setIsEditing] = useState(false);
    const [editingId, setEditingId] = useState<string | null>(null);

    // Form State
    const [year, setYear] = useState(new Date().getFullYear().toString());
    const [sequence, setSequence] = useState('1');
    const [isCurrent, setIsCurrent] = useState(true);

    const openCreateModal = () => {
        setIsEditing(false);
        setEditingId(null);
        setYear(new Date().getFullYear().toString());
        setSequence('1');
        setIsCurrent(true);
        setModalVisible(true);
    };

    const openEditModal = (season: Season) => {
        setIsEditing(true);
        setEditingId(season.id);
        setYear(season.year.toString());
        setSequence(season.sequence.toString());
        setIsCurrent(season.isCurrent);
        setModalVisible(true);
    };

    const handleSave = async () => {
        if (!year || !sequence) {
            Alert.alert('Error', 'Please enter both Year and Sequence.');
            return;
        }

        setSaving(true);
        try {
            const name = `Season ${sequence} ${year}`; // Auto-generate name for consistency

            const seasonData: Season = {
                id: editingId || '', // Generated by DB if new
                name,
                year: parseInt(year),
                sequence: parseInt(sequence),
                isCurrent
            };

            if (isEditing) {
                await updateSeason(seasonData);
                Alert.alert('Success', 'Season updated successfully!');
            } else {
                await addSeason(seasonData);
                Alert.alert('Success', 'Season created successfully!');
            }
            setModalVisible(false);
        } catch (error) {
            Alert.alert('Error', 'Failed to save season.');
        } finally {
            setSaving(false);
        }
    };

    const handleDelete = (id: string, name: string) => {
        Alert.alert(
            "Delete Season",
            `Are you sure you want to delete ${name}? This action cannot be undone and will delete all associated matches.`,
            [
                { text: "Cancel", style: "cancel" },
                {
                    text: "Delete",
                    style: "destructive",
                    onPress: async () => {
                        try {
                            await deleteSeason(id);
                        } catch (e) {
                            Alert.alert("Error", "Could not delete season. It might be linked to other data.");
                        }
                    }
                }
            ]
        );
    };

    return (
        <View className="flex-1 bg-secondary relative">
            <ScrollView contentContainerStyle={{ padding: 20 }}>
                {seasons.map((season) => (
                    <View key={season.id} className="bg-white p-4 rounded-xl mb-4 flex-row justify-between items-center shadow-sm shadow-slate-200">
                        <View>
                            <Text className="text-lg font-black text-slate-900">{season.name}</Text>
                            <View className="flex-row mt-1">
                                <View className="bg-slate-100 px-2 py-0.5 rounded mr-2">
                                    <Text className="text-xs font-bold text-slate-500">Year: {season.year}</Text>
                                </View>
                                {season.isCurrent && (
                                    <View className="bg-green-100 px-2 py-0.5 rounded">
                                        <Text className="text-xs font-bold text-green-600 uppercase">Current</Text>
                                    </View>
                                )}
                            </View>
                        </View>

                        <View className="flex-row items-center gap-2">
                            <TouchableOpacity
                                onPress={() => openEditModal(season)}
                                className="p-2 bg-blue-50 rounded-full"
                            >
                                <Edit size={18} color="#3b82f6" />
                            </TouchableOpacity>
                            <TouchableOpacity
                                onPress={() => handleDelete(season.id, season.name)}
                                className="p-2 bg-red-50 rounded-full"
                            >
                                <Trash2 size={18} color="#ef4444" />
                            </TouchableOpacity>
                        </View>
                    </View>
                ))}

                {seasons.length === 0 && (
                    <View className="items-center py-10">
                        <Text className="text-slate-400 font-bold">No seasons found.</Text>
                    </View>
                )}
            </ScrollView>

            {/* Floating Action Button */}
            <TouchableOpacity
                onPress={openCreateModal}
                className="absolute bottom-10 right-6 w-14 h-14 bg-blue-600 rounded-full items-center justify-center shadow-lg shadow-blue-400 border border-white/20"
            >
                <Plus size={32} color="white" />
            </TouchableOpacity>

            {/* Create/Edit Modal */}
            <Modal
                visible={isModalVisible}
                animationType="slide"
                transparent={true}
                onRequestClose={() => setModalVisible(false)}
            >
                <TouchableWithoutFeedback onPress={() => setModalVisible(false)}>
                    <View className="flex-1 bg-black/50 justify-end">
                        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
                            <View className="bg-white rounded-t-3xl p-6 h-[60%]">
                                <View className="flex-row justify-between items-center mb-6">
                                    <Text className="text-2xl font-black text-slate-900">{isEditing ? 'Edit Season' : 'New Season'}</Text>
                                    <TouchableOpacity onPress={() => setModalVisible(false)}>
                                        <ChevronDown size={28} color="#94a3b8" />
                                    </TouchableOpacity>
                                </View>

                                <Text className="text-slate-500 font-bold mb-2 uppercase text-xs tracking-wider">Year</Text>
                                <TextInput
                                    className="bg-slate-50 p-4 rounded-xl font-bold text-slate-900 mb-4 border border-slate-100"
                                    placeholder="e.g. 2026"
                                    keyboardType="numeric"
                                    value={year}
                                    onChangeText={setYear}
                                />

                                <Text className="text-slate-500 font-bold mb-2 uppercase text-xs tracking-wider">Sequence</Text>
                                <TextInput
                                    className="bg-slate-50 p-4 rounded-xl font-bold text-slate-900 mb-4 border border-slate-100"
                                    placeholder="e.g. 1"
                                    keyboardType="numeric"
                                    value={sequence}
                                    onChangeText={setSequence}
                                />

                                <View className="flex-row items-center justify-between mb-8 bg-slate-50 p-4 rounded-xl border border-slate-100">
                                    <Text className="font-bold text-slate-900">Set as Current Season</Text>
                                    <Switch
                                        value={isCurrent}
                                        onValueChange={setIsCurrent}
                                        trackColor={{ false: '#cbd5e1', true: '#3b82f6' }}
                                        thumbColor={'#ffffff'}
                                    />
                                </View>

                                <TouchableOpacity
                                    onPress={handleSave}
                                    disabled={saving}
                                    className={`py-4 rounded-xl items-center ${saving ? 'bg-blue-400' : 'bg-blue-600'}`}
                                >
                                    {saving ? (
                                        <ActivityIndicator color="white" />
                                    ) : (
                                        <Text className="text-white font-black text-lg uppercase tracking-widest">{isEditing ? 'Update Season' : 'Create Season'}</Text>
                                    )}
                                </TouchableOpacity>
                            </View>
                        </TouchableWithoutFeedback>
                    </View>
                </TouchableWithoutFeedback>
            </Modal>
        </View>
    );
}
